export const DATA = [
        { 
            "department": "ICVD",
            "wards" : [
                {
                    "ward": "GROUND FLOOR  - CCU",
                    "beds": [
                        {"bed": "01A"},
                        {"bed": "02A"},
                        {"bed": "03A"},
                        {"bed": "04A"},
                        {"bed": "05A"},
                        {"bed": "06A"},
                        {"bed": "07A"},
                        {"bed": "08A"},
                        {"bed": "09A"}, 
                        {"bed": "10A"}, 
                        {"bed": "11A"},
                        {"bed": "12A"},
                        {"bed": "13A"},
                        {"bed": "14A"},
                        {"bed": "15A"},
                        {"bed": "16A"},
                        {"bed": "17A"},
                        {"bed": "18A"},
                        {"bed": "19A"}, 
                        {"bed": "20A"}, 
                        {"bed": "23A"} 
                    ]
                },
                {
                    "ward": "I FLOOR - AICU",
                    "beds": [
                        {"bed": "01A"},
                        {"bed": "02A"},
                        {"bed": "03A"},
                        {"bed": "04A"},
                        {"bed": "05A"},
                        {"bed": "06A"},
                        {"bed": "07A"},
                        {"bed": "08A"},
                        {"bed": "09A"}, 
                        {"bed": "10A"}, 
                        {"bed": "11A"},
                        {"bed": "12A"},
                        {"bed": "13A"},
                        {"bed": "14A"},
                        {"bed": "15A"},
                        {"bed": "16A"},
                        {"bed": "17A"},
                        {"bed": "18A"},
                        {"bed": "19A"}, 
                        {"bed": "20A"}
                    ]
                },
                {
                    "ward": "II FLOOR - MGW",
                    "beds": [
                        {"bed": "01A"},
                        {"bed": "02A"},
                        {"bed": "03A"},
                        {"bed": "04A"},
                        {"bed": "05A"},
                        {"bed": "06A"},
                        {"bed": "07A"},
                        {"bed": "08A"},
                        {"bed": "09A"}, 
                        {"bed": "10A"}, 
                        {"bed": "11A"},
                        {"bed": "12A"},
                        {"bed": "13A"},
                        {"bed": "14A"},
                        {"bed": "15A"},
                        {"bed": "16A"},
                        {"bed": "17A"},
                        {"bed": "18A"},
                        {"bed": "19A"}, 
                        {"bed": "20A"}
                    ]
                },
                {
                    "ward": "II FLOOR - PGW",
                    "beds": [
                        {"bed": "01A"},
                        {"bed": "02A"},
                        {"bed": "03A"},
                        {"bed": "04A"},
                        {"bed": "05A"},
                        {"bed": "06A"},
                        {"bed": "07A"},
                        {"bed": "08A"},
                        {"bed": "09A"}, 
                        {"bed": "10A"}, 
                        {"bed": "11A"},
                        {"bed": "12A"},
                        {"bed": "13A"},
                        {"bed": "14A"},
                        {"bed": "15A"},
                        {"bed": "16A"},
                        {"bed": "17A"},
                        {"bed": "18A"},
                        {"bed": "19A"}, 
                        {"bed": "20A"}
                    ]
                },
                {
                    "ward": "II FLOOR - PREMIUM/INTL.WARD",
                    "beds": [
                        {"bed": "211A"},
                        {"bed": "212A"},
                        {"bed": "213A"},
                        {"bed": "214A"},
                    ]
                },
                {
                    "ward": "II FLOOR - STEP DOWN ICU",
                    "beds": [
                        {"bed": "01A"},
                        {"bed": "02A"},
                        {"bed": "03A"},
                        {"bed": "04A"},
                        {"bed": "05A"},
                        {"bed": "06A"},
                        {"bed": "07A"},
                        {"bed": "08A"},
                        {"bed": "09A"}, 
                        {"bed": "10A"}, 
                        {"bed": "11A"},
                        {"bed": "12A"},
                        {"bed": "13A"},
                        {"bed": "14A"},
                        {"bed": "15A"},
                        {"bed": "16A"},
                        {"bed": "17A"},
                        {"bed": "18A"},
                        {"bed": "19A"}, 
                        {"bed": "20A"},
                        {"bed": "21A"},
                        {"bed": "22A"},
                        {"bed": "23A"},
                    ]
                },
                {
                    "ward": "II FLOOR",
                    "beds": [
                        {"bed": "201A"},
                        {"bed": "202A"},
                        {"bed": "203A"},
                        {"bed": "204A"},
                        {"bed": "205A"},
                        {"bed": "206A"},
                        {"bed": "207A"},
                        {"bed": "208A"},
                        {"bed": "209A"}, 
                        {"bed": "210A"}, 
        
                    ]
                },
                {
                    "ward": "III FLOOR (EXECUTIVE FLOOR)",
                    "beds": [
                        {"bed": "301A"},
                        {"bed": "301B"},
                        {"bed": "302A"},
                        {"bed": "302B"},
                        {"bed": "303A"},
                        {"bed": "303B"},
                        {"bed": "304A"},
                        {"bed": "304B"},
                        {"bed": "305A"},
                        {"bed": "305B"},
                        {"bed": "306A"},
                        {"bed": "306B"},
                        {"bed": "307A"},
                        {"bed": "307B"},
                        {"bed": "308A"},
                        {"bed": "308B"},
                        {"bed": "309A"},
                        {"bed": "309B"},
                        {"bed": "310A"},
                        {"bed": "310B"},
                        {"bed": "311A"},
                        {"bed": "311B"},
                        {"bed": "312A"},
                        {"bed": "312B"},
                        {"bed": "313A"},
                        {"bed": "313B"},
                        {"bed": "314A"},
                        {"bed": "314B"},
                        {"bed": "315A"},
                        {"bed": "315B"},
                        {"bed": "316A"},
                        {"bed": "316B"},
                        {"bed": "317A"},
                        {"bed": "317B"},
                        {"bed": "318A"},
                        {"bed": "318B"},
                        {"bed": "319A"},
                        {"bed": "319B"},
                        {"bed": "320A"},
                        {"bed": "320B"},
                    ]
                }
            ]
        }
    ];
  
    export default DATA;